import { readFile } from 'node:fs/promises';

const files = {
  app: await readFile(new URL('../app.js', import.meta.url), 'utf8'),
  index: await readFile(new URL('../index.html', import.meta.url), 'utf8'),
  styles: await readFile(new URL('../kpi-order.css', import.meta.url), 'utf8'),
  accountFunction: await readFile(new URL('../supabase/functions/manage-account/index.ts', import.meta.url), 'utf8'),
  branchLock: await readFile(new URL('../supabase/migrations/20260915193000_lock_staff_branch.sql', import.meta.url), 'utf8'),
  backupRestore: await readFile(new URL('../supabase/migrations/20260915194000_operational_backup_restore.sql', import.meta.url), 'utf8'),
  fifoSellingPrices: await readFile(new URL('../supabase/migrations/20260915198000_fifo_batch_selling_prices.sql', import.meta.url), 'utf8'),
  safeArchiving: await readFile(new URL('../supabase/migrations/20260915199000_safe_product_archiving.sql', import.meta.url), 'utf8'),
  transferSellingPrices: await readFile(new URL('../supabase/migrations/20260915200000_transfer_fifo_selling_prices.sql', import.meta.url), 'utf8'),
  openingCreditBalances: await readFile(new URL('../supabase/migrations/20260917001000_customer_opening_credit_balances.sql', import.meta.url), 'utf8'),
  bundles: await readFile(new URL('../supabase/migrations/20260918000000_bundles_returns_replacements.sql', import.meta.url), 'utf8'),
  multiLineTransfers: await readFile(new URL('../supabase/migrations/20260918003000_multi_line_bundle_transfers.sql', import.meta.url), 'utf8'),
  transferBatchActions: await readFile(new URL('../supabase/migrations/20260918004000_transfer_batch_actions.sql', import.meta.url), 'utf8'),
  salesReturns: await readFile(new URL('../supabase/migrations/20260918005000_complete_sales_return_workflow.sql', import.meta.url), 'utf8'),
  mixedSalesReturns: await readFile(new URL('../supabase/migrations/20260918007000_mixed_sales_return_actions.sql', import.meta.url), 'utf8'),
  sameItemReplacements: await readFile(new URL('../supabase/migrations/20260918008000_same_item_replacements.sql', import.meta.url), 'utf8'),
  bundleReturnComponents: await readFile(new URL('../supabase/migrations/20260918009000_resolve_bundle_return_components.sql', import.meta.url), 'utf8'),
  refundReplacementOnly: await readFile(new URL('../supabase/migrations/20260918010000_refund_replacement_sales_returns.sql', import.meta.url), 'utf8'),
  dailySpotCash: await readFile(new URL('../supabase/migrations/20260929100000_daily_spot_cash.sql', import.meta.url), 'utf8'),
  dailyExpenses: await readFile(new URL('../supabase/migrations/20260929110000_daily_expenses.sql', import.meta.url), 'utf8'),
  dailyOperationsBackup: await readFile(new URL('../supabase/migrations/20260929120000_backup_daily_operations.sql', import.meta.url), 'utf8').catch(() => ''),
  salePriceOverrides: await readFile(new URL('../supabase/migrations/20261001000000_sale_price_overrides.sql', import.meta.url), 'utf8'),
  branchPriceOverrides: await readFile(new URL('../supabase/migrations/20261001010000_branch_selling_price_overrides.sql', import.meta.url), 'utf8'),
};

const checks = [
  ['staff branch selector is locked during editing', /type === 'editStaff'[\s\S]*branch is locked after account creation/i.test(files.app)],
  ['staff updates do not submit a branch ID', /updateStaffAccount[\s\S]*full_name: fullName, permissions/.test(files.accountFunction)],
  ['database trigger prevents staff branch changes', /prevent_staff_branch_change/.test(files.branchLock)],
  ['administrator edits use the protected account function', /action === 'updateAdminAccount'[\s\S]*functions\.invoke\('manage-account'/.test(files.app)],
  ['administrator password resets require a password change on next login', /Reset administrator password/.test(files.accountFunction)],
  ['administrator edit passwords reach the account function', /body\.newPassword/.test(files.accountFunction)],
  ['backup and restore actions require the administrator account function', /createOperationalBackup[\s\S]*restoreOperationalBackup/.test(files.accountFunction)],
  ['restore is transactional in the database', /restore_pos_backup/.test(files.backupRestore)],
  ['stock-in selling prices are stored as FIFO batches', /selling_price_input[\s\S]*inventory_cost_batches/.test(files.fifoSellingPrices)],
  ['checkout allocates each sale to FIFO batch prices', /sale_item_price_allocations[\s\S]*qty_remaining/.test(files.fifoSellingPrices)],
  ['cart renders mixed FIFO batch prices', /getCartPriceBreakdown[\s\S]*Batch Selling Price/.test(files.app)],
  ['product price overrides are sent to checkout', /openProductPriceOverride[\s\S]*sellingPriceOverride[\s\S]*items: cart\.map[\s\S]*price: Number\(item\.sellingPriceOverride\)/.test(files.app) && /productPriceOverrideDialog/.test(files.index)],
  ['registered products offer a persistent selling-price override action', /data-product-price-override[\s\S]*openProductPriceOverride[\s\S]*setProductSellingPriceOverride/.test(files.app) && /selling_price_override/.test(files.branchPriceOverrides)],
  ['database records optional cart price overrides as the sale allocation price', /requested_price := case when line \? 'price'[\s\S]*coalesce\(requested_price, batch_row\.selling_price\)[\s\S]*sale_item_price_allocations/.test(files.salePriceOverrides)],
  ['catalog price follows the cart batch currently reached', /displayedSellingPrice[\s\S]*breakdown\[breakdown\.length - 1\]/.test(files.app)],
  ['used products are archived instead of deleting historical stock-ins', /stock_ins[\s\S]*Archived product/.test(files.safeArchiving)],
  ['transfers preserve each FIFO selling-price batch', /transfer_batch_allocations[\s\S]*selling_price[\s\S]*Received FIFO selling-price transfer/.test(files.transferSellingPrices)],
  ['customer migration balances use a separate audited credit account', /customer_credit_accounts[\s\S]*opening_balance[\s\S]*create_customer_with_opening_balance/.test(files.openingCreditBalances)],
  ['opening balance payments cannot be mistaken for sales', /credit_payments_one_credit_source[\s\S]*record_credit_payment/.test(files.openingCreditBalances)],
  ['operational backups include opening credit accounts', /customerCreditAccounts/.test(files.accountFunction)],
  ['operational backups include daily spot cash and daily expenses', /from\('daily_spot_cash'\)[\s\S]*from\('daily_expenses'\)/.test(files.accountFunction) && /dailySpotCash: rows\[20\][\s\S]*dailyExpenses: rows\[21\]/.test(files.accountFunction)],
  ['operational restore restores supplied daily spot cash and expenses transactionally', /restore_pos_backup_daily_operations/.test(files.dailyOperationsBackup) && /delete from public\.daily_spot_cash[\s\S]*insert into public\.daily_spot_cash/.test(files.dailyOperationsBackup) && /delete from public\.daily_expenses[\s\S]*insert into public\.daily_expenses/.test(files.dailyOperationsBackup)],
  ['bundle recipes accept only individual component products', /Bundle components must be active individual products/.test(files.bundles)],
  ['bundle availability is calculated from component stock', /get_branch_bundle_availability[\s\S]*floor\(coalesce\(inventory\.qty/.test(files.bundles)],
  ['product form saves bundle price and component recipes', /save_bundle_components[\s\S]*bundleComponents/.test(files.app)],
  ['virtual bundles cannot be stocked in directly', /filter\(\(item\) => item\.productType !== 'bundle'\)/.test(files.app)],
  ['multi-line transfers validate combined component demand before drafting', /create_transfer_batch[\s\S]*required_components[\s\S]*Insufficient source stock/.test(files.multiLineTransfers)],
  ['bundle transfers enable the destination bundle automatically', /branch_products[\s\S]*destination_branch_id_input[\s\S]*product_row\.bundle_price/.test(files.multiLineTransfers)],
  ['transfer form accepts multiple individual products and bundles', /readTransferLines_[\s\S]*createTransferBatch/.test(files.app)],
  ['transfer batches dispatch, receive, and cancel all component lines atomically', /process_transfer_batch[\s\S]*dispatch_transfer[\s\S]*receive_transfer[\s\S]*cancel_transfer/.test(files.transferBatchActions)],
  ['sales returns enter quarantine before inventory disposition', /receive_sale_return[\s\S]*inventory_return_lots[\s\S]*quarantine/.test(files.salesReturns)],
  ['sales-return restocks create FIFO batches from quarantine lots', /resolve_return_item[\s\S]*inventory_cost_batches[\s\S]*lot\.unit_cost/.test(files.salesReturns)],
  ['replacement releases use FIFO inventory allocation', /release_sale_replacement[\s\S]*inventory_cost_batches[\s\S]*qty_remaining/.test(files.salesReturns)],
  ['sales history exposes return, refund, and replacement actions', /data-manage-sale-return/.test(files.app) && /receiveSaleReturn/.test(files.app) && /releaseSaleReplacement/.test(files.app)],
  ['sales history shows the separate return-history action only for recorded returns', /hasReturnHistory = saleReturns\.some[\s\S]*data-view-sale-returns[\s\S]*openSaleReturnHistoryDialog/.test(files.app) && /saleReturnHistoryDialog[\s\S]*saleReturnHistoryExisting/.test(files.index)],
  ['sales report calculates net sales from gross sales, refunds, and expenses', /const netSales = Math\.max\(totalSales - totalRefunds - totalExpenses, 0\);/.test(files.app)],
  ['sales report calculates net income at 20% of net sales and shows net sales in the footer', /const netIncome = netSales \* 0\.20;/.test(files.app) && /<span>Net Sales:<\/span>[\s\S]*Net Income:[\s\S]*money\(netIncome\)/.test(files.app)],
  ['daily spot cash protects branch opening floats and staff access', /dailySpotCash/.test(files.app) && /daily_spot_cash/.test(files.app) && /daily_spot_cash/.test(files.dailySpotCash) && /can_access_branch\(target_branch_id\)/.test(files.dailySpotCash) && /has_permission\('dailySpotCash'\)/.test(files.dailySpotCash) && /deleted_at/.test(files.dailySpotCash)],
  ['daily expenses can be granted to staff and saved per branch', /dailyExpenses:\s*\{\s*key:\s*'dailyExpenses'/.test(files.app) && /dailyExpenses/.test(files.accountFunction) && /daily_expenses/.test(files.dailyExpenses) && /create_daily_expense/.test(files.app) && /can_access_branch\(target_branch_id\)/.test(files.dailyExpenses) && /has_permission\('dailyExpenses'\)/.test(files.dailyExpenses)],
  ['staff add and edit forms offer both branch-operation permissions', /\['dailySpotCash', 'Daily Spot Cash'\]/.test(files.app) && /\['dailyExpenses', 'Daily Expenses'\]/.test(files.app)],
  ['staff permission cards follow the sidebar order', /\['transfers', 'Stock Transfers'\],[\s\S]*\['dailySpotCash', 'Daily Spot Cash'\],[\s\S]*\['dailyExpenses', 'Daily Expenses'\],[\s\S]*\['customers', 'Customers'\]/.test(files.app)],
  ['daily expenses loads the current click handler bundle', /app\.js\?v=lpg-refill-inventory-1/.test(files.index) && /addDailyExpenseButton'\)\?\.addEventListener\('click', \(\) => openForm\('dailyExpenses'\)\)/.test(files.app)],
  ['dashboard KPI ordering loads the current stylesheet', /kpi-order\.css\?v=1/.test(files.index)],
  ['daily expense modal has its category list before rendering', /const DAILY_EXPENSE_CATEGORIES = \[/.test(files.app) && /DAILY_EXPENSE_CATEGORIES\.map\(/.test(files.app)],
  ['dashboard combines cash collected and today spot cash less expenses', /const todaySpotCash = dailySpotCash[\s\S]*businessDate === todayKey[\s\S]*openingCash/.test(files.app) && /const todayCashOnHand = todayCashCollected \+ todaySpotCash - todayExpenses;/.test(files.app) && /Cash Collected \+ Today\'s Spot Cash - Expenses/.test(files.app) && /Today\'s Spot Cash[\s\S]*money\(todaySpotCash\)/.test(files.app)],
  ['dashboard cards follow the financial flow before stock attention', /\.dashboard-summary-grid > \.kpi-cashonhand\s*\{\s*order:\s*4;/.test(files.styles) && /\.dashboard-summary-grid > \.kpi-netsales\s*\{\s*order:\s*5;/.test(files.styles) && /\.dashboard-summary-grid > \.kpi-stock\s*\{\s*order:\s*8;/.test(files.styles)],
  ['sales report shows spot cash and cash on hand less expenses', /const totalSpotCash = dailySpotCash[\s\S]*businessDate < dateFrom[\s\S]*openingCash/.test(files.app) && /const totalCashOnHand = netCashCollected \+ totalSpotCash - totalExpenses;/.test(files.app) && /<span class="kpi-label">Spot Cash<\/span>[\s\S]*money\(totalSpotCash\)/.test(files.app) && /<span>Net Sales:<\/span>[\s\S]*money\(netSales\)/.test(files.app) && /Net cash collected \+ spot cash - expenses/.test(files.app)],
  ['printable sales report KPI cards group financial totals before return activity', /\.report-kpi-grid > \.report-kpi-card:nth-child\(9\)\s*\{\s*order:\s*4;/.test(files.app) && /\.report-kpi-grid > \.report-kpi-card:nth-child\(4\)\s*\{\s*order:\s*9;/.test(files.app)],
  ['sales report includes return and replacement activity', /Return & Replacement Activity[\s\S]*returnOutcomes/.test(files.app)],
  ['sales return report itemizes each returned line', /returnsInPeriod\.flatMap[\s\S]*Returned Item[\s\S]*line\.actionType[\s\S]*line\.condition/.test(files.app)],
  ['a sale return accepts only refund or same-item replacement actions', /action_value not in \('refund', 'replacement'\)/.test(files.refundReplacementOnly) && /option value="refund">Refund[\s\S]*option value="replacement">Replace/.test(files.app) && !/option value="return">Return Only/.test(files.app)],
  ['cumulative refunds cannot exceed the original sale', /prior_refunds[\s\S]*remaining refundable amount/.test(files.mixedSalesReturns)],
  ['replacements are restricted to the original item and returned quantity', /replacement_product_id_value is distinct from sale_item_row\.product_id[\s\S]*replacement_qty_value <> qty_value/.test(files.sameItemReplacements) && /Same item:[\s\S]*data-replacement-product[\s\S]*type="hidden"/.test(files.app)],
  ['only refund lines submit a refund amount', /action === 'refund'[\s\S]*refundInput\.value[\s\S]*actionType === 'refund' \? Number\(document\.querySelector\(`\[data-refund-amount=/.test(files.app)],
  ['quarantine disposition actions are labeled buttons', /resolve-btn-text">Restock[\s\S]*resolve-btn-text">Supplier Return[\s\S]*resolve-btn-text">Dispose/.test(files.app)],
  ['bundle returns resolve their quarantined components independently', /resolve_bundle_return_component[\s\S]*target_product_id[\s\S]*inventory_return_lots/.test(files.bundleReturnComponents) && /inventoryReturnLots[\s\S]*data-resolve-bundle-return-component[\s\S]*resolveBundleReturnComponent_/.test(files.app)],
  ['dashboard operational lists are limited to five ordered records', /topProducts[\s\S]*slice\(0, 5\)[\s\S]*attentionStock[\s\S]*slice\(0, 5\)[\s\S]*pendingTransfers[\s\S]*slice\(0, 5\)[\s\S]*recentSales[\s\S]*slice\(0, 5\)/.test(files.app)],
  ['LPG bundle rows show filled and empty tank counts', /inventoryRole[\s\S]*tankInventory[\s\S]*bundle-tank-inventory[\s\S]*Filled[\s\S]*Empty/.test(files.app)],
  ['LPG bundle checkouts flag the automatic empty-tank return', /item\.tankInventory \? \{ emptyReturn: true \}/.test(files.app)],
];

const failures = checks.filter(([, passed]) => !passed).map(([name]) => name);
if (failures.length) {
  console.error(`POS checks failed: ${failures.join('; ')}`);
  process.exit(1);
}

console.log(`POS checks passed: ${checks.length}`);
