alter table public.profiles drop constraint if exists profiles_permissions_check;
alter table public.profiles add constraint profiles_permissions_check check (permissions <@ array['pos','products','inventory','transfers','customers','credits','sales','inventoryReports','dailySpotCash','dailyExpenses']);
create table public.daily_expenses (
  expense_id uuid primary key default gen_random_uuid(), branch_id text not null references public.branches(branch_id), business_date date not null,
  category text not null, description text not null default '', amount numeric(12,2) not null check(amount >= 0), receipt_reference text not null default '',
  created_at timestamptz not null default now(), created_by uuid not null references public.profiles(user_id), updated_at timestamptz not null default now(), updated_by uuid not null references public.profiles(user_id), deleted_at timestamptz, deleted_by uuid references public.profiles(user_id)
);
alter table public.daily_expenses enable row level security;
create policy "daily expenses read permitted branch" on public.daily_expenses for select to authenticated using (deleted_at is null and public.has_permission('dailyExpenses') and public.can_access_branch(branch_id));
create or replace function public.create_daily_expense(target_branch_id text,target_business_date date,target_category text,target_description text,target_amount numeric,target_receipt_reference text default '') returns public.daily_expenses language plpgsql security definer set search_path=public as $$ declare r public.daily_expenses; begin if not public.has_permission('dailyExpenses') or not public.can_access_branch(target_branch_id) then raise exception 'Your account does not have access to Daily Expenses.'; end if; perform public.assert_active_branch(target_branch_id); if target_business_date is null or coalesce(trim(target_category),'')='' or target_amount is null or target_amount<0 then raise exception 'Enter a valid date, category, and cash amount.'; end if; insert into public.daily_expenses(branch_id,business_date,category,description,amount,receipt_reference,created_by,updated_by) values(target_branch_id,target_business_date,trim(target_category),coalesce(trim(target_description),''),target_amount,coalesce(trim(target_receipt_reference),''),auth.uid(),auth.uid()) returning * into r; insert into public.account_audit(actor_id,action,target_id,details) values(auth.uid(),'Created daily expense',r.expense_id::text,r.category||' / '||r.amount::text); return r; end; $$;
revoke all on function public.create_daily_expense(text,date,text,text,numeric,text) from public;
grant execute on function public.create_daily_expense(text,date,text,text,numeric,text) to authenticated;
create or replace function public.update_daily_expense(target_expense_id uuid,target_business_date date,target_category text,target_description text,target_amount numeric,target_receipt_reference text default '') returns public.daily_expenses language plpgsql security definer set search_path=public as $$ declare r public.daily_expenses; begin select * into r from public.daily_expenses where expense_id=target_expense_id and deleted_at is null for update; if not found then raise exception 'Daily Expense record not found.'; end if; if not public.has_permission('dailyExpenses') or not public.can_access_branch(r.branch_id) then raise exception 'Your account does not have access to Daily Expenses.'; end if; if target_business_date is null or coalesce(trim(target_category),'')='' or target_amount is null or target_amount<0 then raise exception 'Enter a valid date, category, and cash amount.'; end if; update public.daily_expenses set business_date=target_business_date,category=trim(target_category),description=coalesce(trim(target_description),''),amount=target_amount,receipt_reference=coalesce(trim(target_receipt_reference),''),updated_at=now(),updated_by=auth.uid() where expense_id=target_expense_id returning * into r; insert into public.account_audit(actor_id,action,target_id,details) values(auth.uid(),'Updated daily expense',r.expense_id::text,r.category||' / '||r.amount::text); return r; end; $$;
create or replace function public.delete_daily_expense(target_expense_id uuid) returns void language plpgsql security definer set search_path=public as $$ declare r public.daily_expenses; begin select * into r from public.daily_expenses where expense_id=target_expense_id and deleted_at is null for update; if not found then raise exception 'Daily Expense record not found.'; end if; if not public.has_permission('dailyExpenses') or not public.can_access_branch(r.branch_id) then raise exception 'Your account does not have access to Daily Expenses.'; end if; update public.daily_expenses set deleted_at=now(),deleted_by=auth.uid(),updated_at=now(),updated_by=auth.uid() where expense_id=target_expense_id; insert into public.account_audit(actor_id,action,target_id,details) values(auth.uid(),'Deleted daily expense',r.expense_id::text,r.category||' / '||r.amount::text); end; $$;
revoke all on function public.update_daily_expense(uuid,date,text,text,numeric,text), public.delete_daily_expense(uuid) from public;
grant execute on function public.update_daily_expense(uuid,date,text,text,numeric,text), public.delete_daily_expense(uuid) to authenticated;
